version: "3"
services:
  db2:
    image: pxc:latest
    ports:
      - "23307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster1
      - CLUSTER_JOIN=node1
    # depends_on:
    #   - db1
    volumes:
      - v2:/var/lib/mysql
      - backup:/data
      - /home/leilei/pxc/conf:/etc/mysql/conf.d
    restart: always
    networks:
      pxc-network:
        ipv4_address: "172.19.0.3"
    container_name: "node2" 
  db3:
    image: pxc:latest
    ports:
      - "23308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster1
      - CLUSTER_JOIN=node1
    # depends_on:
    #   - db1
    volumes:
      - v3:/var/lib/mysql
      - backup:/data
      - /home/leilei/pxc/conf:/etc/mysql/conf.d
    restart: always
    networks:
      pxc-network:
        ipv4_address: "172.19.0.4"
    container_name: "node3" 
  db4:
    image: pxc:latest
    ports:
      - "23309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster1
      - CLUSTER_JOIN=node1
    # depends_on:
    #   - db1
    volumes:
      - v4:/var/lib/mysql
      - backup:/data
      - /home/leilei/pxc/conf:/etc/mysql/conf.d
    restart: always
    networks:
      pxc-network:
        ipv4_address: "172.19.0.5"
    container_name: "node4" 
  db5:
    image: pxc:latest
    ports:
      - "23310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster1
      - CLUSTER_JOIN=node1
    # depends_on:
    #   - db1
    volumes:
      - v5:/var/lib/mysql
      - backup:/data
      - /home/leilei/pxc/conf:/etc/mysql/conf.d
    restart: always
    networks:
      pxc-network:
        ipv4_address: "172.19.0.6"
    container_name: "node5" 
  h1:
    image: myhaproxy:latest
    ports:
      - "4001:8888"
      - "4002:3306"
    volumes:
      - /home/leilei/haproxy/h1:/usr/local/etc/haproxy
    networks:
      pxc-network:
        ipv4_address: "172.19.0.7"
    restart: always
    depends_on:
      - db2
      - db3
      - db4
      - db5
    container_name: "h1" 
  h2:
    image: myhaproxy:latest
    ports:
      - "4003:8888"
      - "4004:3306"
    volumes:
      - /home/leilei/haproxy/h2:/usr/local/etc/haproxy
    networks:
      pxc-network:
        ipv4_address: "172.19.0.8"
    restart: always
    depends_on:
      - db2
      - db3
      - db4
      - db5
    container_name: "h2" 
volumes:
  v2:
  v3:
  v4:
  v5:
  backup: