version: "3"
services:
  node1:
    image: pxc:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster-1
    volumes:
      - db1:/var/lib/mysql
      - backup:/data
      - ./conf:/etc/mysql/conf.d
      - ./initialdb:/docker-entrypoint-initdb.d
    networks:
      mysql-network:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  node2:
    image: pxc:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=cluster-1
      - CLUSTER_JOIN=node1
    volumes:
      - db2:/var/lib/mysql
      - backup:/data
      - ./conf:/etc/mysql/conf.d
      - ./initialdb:/docker-entrypoint-initdb.d
    networks:
      mysql-network:
    depends_on:
      - node1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  ha:
    image: haproxy:db
    ports:
      - "8888"
      - "8000"
    volumes:
      - ./haproxy/h1:/usr/local/etc/haproxy
    privileged: true
    networks:
      mysql-network:
    depends_on:
      - node1
      - node2
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  db1:
  backup:
networks:
  mysql-network: