version: "3.7"
services:
  node1:
    image: pxc:latest
    ports:
      - "6033:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iiecas
      - XTRABACKUP_PASSWORD=iiecas
      - CLUSTER_NAME=pxc-cluster
    volumes:
      - db1:/var/lib/mysql
      - backup:/data
      - /etc/localtime:/etc/localtime
    networks:
      mysql-network:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  ha:
    image: haproxy:web
    volumes:
      - /home/iiebc/pxc/sample/haproxy:/usr/local/etc/haproxy
    networks:
      - mysql-network
    depends_on:
      - node1
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  db1:
  backup:

networks:
  mysql-network:
    driver: overlay
    attachable: true